[global]
db_path              = /var/tmp/fixmon-live.db
metrics_port         = 9109
poll_interval_ms     = 100
stale_after_multiple = 1

from_beginning       = false

quickfix_config = /mnt/c/ADSS/tools/FIXMessageSender/FIXMessageSender/build/debug/quickfix_config.cfg
quickfix_config = /mnt/c/ADSS/tools/FIXMessageSender_Acceptor/quickfix_config.cfg

[session]
begin_string   = FIX.4.4
sender_comp_id = FIX_QA_Acceptor
target_comp_id = BACK_OFFICE_QA_ACCEPTOR
message_log    = /mnt/c/ADSS/tools/FIXMessageSender_Acceptor/server_qfj/FIX.4.4-FIX_QA_Acceptor-BACK_OFFICE_QA_ACCEPTOR.messages.current.log
event_log      = /mnt/c/ADSS/tools/FIXMessageSender_Acceptor/server_qfj/FIX.4.4-FIX_QA_Acceptor-BACK_OFFICE_QA_ACCEPTOR.event.current.log